import type { BrandConfig, Treatment, TreatmentCategory } from "./types";

/* ====================================================================== *
 * STARTER BRAND: the base for every new clinic site.
 *
 * Do not edit this file for a client. Run `npm run new-brand -- <id> "Clinic Name"`
 * to copy it to brands/<id>.ts, then change the SETTINGS block below. Everything
 * the site shows (name, logo, colours, reels, photos, contact, copy) comes from
 * this one file plus the assets in public/brands/<id>/ and posts in content/<id>/blog/.
 * Search for PLACEHOLDER to find what still needs real client content.
 * ====================================================================== */

/* ---------------------------- SETTINGS ---------------------------- */
const ID = "starter"; // must match the file name, public/brands/<id>/ and content/<id>/blog/
const NAME = "Your Clinic"; // brand name used in titles, copy, WhatsApp message
const TAGLINE = "Aesthetic Dermatology & Wellness";
const CITY = "Your City";
const SITE_URL = "https://www.example.com"; // production URL (canonical, sitemap, Open Graph)

const ASSETS = `/brands/${ID}`; // folder: public/brands/<id>/
const LOGO = `${ASSETS}/logo.svg`; // header/footer logo
const FAVICON = `${ASSETS}/favicon.svg`;
const OG_IMAGE: string | undefined = undefined; // optional, e.g. `${ASSETS}/og.jpg` (1200x630)
const EMBLEM: BrandConfig["mark"] = undefined; // optional icon beside the wordmark, e.g. { src: `${ASSETS}/mark.png`, width: 76, height: 90 }
const WORDMARK = { line1: "YOUR", line2: "CLINIC" }; // text logo used when there is no EMBLEM

const COLORS = {
  primary: "#2F5D62", // buttons, headings
  accent: "#8A6F4E", // links, highlights (keep 4.5:1 contrast on background)
  background: "#FFFFFF",
  surface: "#F6F4F0",
  text: "#1C1917",
  muted: "#6B645E",
  line: "#E7E3DD",
};
const FONTS: BrandConfig["fonts"] = { display: "cormorant", body: "jost" }; // cormorant | jost | marcellus | manrope | playfair | inter | montserrat

const CONTACT = {
  phone: "+91 00000 00000", // PLACEHOLDER: display format. Call buttons stay hidden while it starts "+91 00000"
  phoneTel: "+910000000000", // PLACEHOLDER
  whatsapp: "910000000000", // PLACEHOLDER: digits only, with country code
  email: "hello@example.com", // PLACEHOLDER
  address: { lines: ["Street address line 1", "Area"], city: CITY, state: "State", postalCode: "000000", country: "IN" }, // PLACEHOLDER
  mapEmbedUrl: "https://www.google.com/maps?q=Your+Clinic&output=embed", // PLACEHOLDER: Google Maps > Share > Embed a map
  geo: undefined as BrandConfig["geo"], // optional { lat, lng }
  hours: [
    { days: "Monday – Saturday", hours: "10:00 am – 7:00 pm" }, // PLACEHOLDER
    { days: "Sunday", hours: "By appointment" },
  ],
  social: { instagram: "https://www.instagram.com/", facebook: "", youtube: "", linkedin: "" },
};

/** Instagram reels shown as video reviews. Paste each reel URL. Empty list shows a "watch on Instagram" prompt. */
const REELS: BrandConfig["videoReviews"] = [
  // { name: "Patient name", instagramUrl: "https://www.instagram.com/reel/XXXXXXXXXXX/", treatment: "Microneedling" },
];

/** Hero background, doctor portrait. Leave `src` undefined to use stock / hide. */
const HERO_IMAGE = { alt: `${NAME} clinic`, src: undefined as string | undefined }; // e.g. `${ASSETS}/hero.jpg`
const DOCTOR_IMAGE = { alt: "Doctor portrait", src: undefined as string | undefined }; // e.g. `${ASSETS}/doctor.jpg`

/** Real photos for the Gallery page (needs 3+ for the nav link to appear). */
const GALLERY: BrandConfig["gallery"] = [
  // { src: `${ASSETS}/gallery-1.jpg`, alt: "Treatment room", categorySlug: "skin" },
];

const GOOGLE_RATING = { score: 0, count: 0, url: undefined as string | undefined }; // hidden while count is 0
/* -------------------------- END SETTINGS -------------------------- */

const img = (alt: string, src?: string) => ({ alt, src });
const faq = (q: string, a: string) => ({ q, a });
const disclaimer =
  "Results vary from person to person. Treatments are performed by qualified professionals after a consultation and suitability assessment.";

const steps = [
  { title: "Consultation", text: "A discussion of your goals, medical history and suitability." },
  { title: "Planning", text: "A personalised plan, with options and expectations explained." },
  { title: "Treatment", text: "The procedure is carried out with attention to comfort." },
  { title: "Aftercare", text: "Clear guidance and follow-up to support recovery." },
];
const recovery = [
  "Mild redness, swelling or sensitivity can occur and usually settles quickly.",
  "Follow the aftercare instructions given at your appointment and use daily sun protection.",
];

const treat = (x: Omit<Treatment, "steps" | "recovery" | "image" | "faqs"> & { faqs: [string, string][] }): Treatment => ({
  ...x,
  steps,
  recovery,
  faqs: x.faqs.map(([q, a]) => faq(q, a)),
  image: img(x.title), // add `src` to use your own photo; otherwise a stock photo fills in
});

/* Treatments and categories: edit, add or delete freely. Slugs become URLs (/treatments/<slug>). */
const skin: TreatmentCategory = {
  slug: "skin",
  title: "Skin",
  blurb: "Facials, peels and skin-quality treatments tailored to you.", // PLACEHOLDER
  image: img("Skin treatments"),
  treatments: [
    treat({
      slug: "hydrating-facial",
      title: "Hydrating Facial",
      short: "A cleanse, exfoliation and hydration facial for fresh-looking skin.",
      long: ["A hydrating facial cleanses, exfoliates and infuses moisture-rich serums, chosen to suit your skin after a short assessment."],
      benefits: ["Deep cleansing", "Improved hydration", "No significant downtime"],
      suitableFor: ["Dull or dehydrated skin", "Pre-event skin prep", "Regular maintenance"],
      duration: "45 – 60 minutes",
      faqs: [["How often can I have one?", "Typically every few weeks; your clinician will advise."]],
      related: ["microneedling"],
    }),
    treat({
      slug: "microneedling",
      title: "Microneedling",
      short: "Controlled micro-channels that encourage the skin's own renewal.",
      long: ["Microneedling uses fine needles to stimulate natural repair, commonly used for texture, acne marks and overall skin quality."],
      benefits: ["Supports smoother texture", "Helps with mild scarring"],
      suitableFor: ["Acne marks", "Uneven texture"],
      duration: "60 minutes",
      faqs: [["Does it hurt?", "A numbing cream is used so most people are comfortable."]],
      related: ["hydrating-facial"],
    }),
  ],
};

const injectables: TreatmentCategory = {
  slug: "injectables",
  title: "Injectables",
  blurb: "Fillers and toxins by qualified doctors.", // PLACEHOLDER
  image: img("Injectables"),
  treatments: [
    treat({
      slug: "dermal-fillers",
      title: "Dermal Fillers",
      short: "Hyaluronic acid fillers to restore volume and soften lines, subtly.",
      long: ["Dermal fillers are injectable gels used to restore volume or soften lines. Placement is planned around facial balance, with a conservative approach."],
      benefits: ["Restores lost volume", "Subtle, balanced enhancement"],
      suitableFor: ["Volume loss", "Lip or cheek definition"],
      duration: "30 – 45 minutes",
      faqs: [["How long do fillers last?", "It depends on the product and area; your doctor will explain."]],
      related: ["botox"],
    }),
    treat({
      slug: "botox",
      title: "Botox",
      short: "Botulinum toxin to soften expression lines, tailored to your face.",
      long: ["Botulinum toxin relaxes specific muscles to soften expression lines. Dose and placement are individualised for natural movement."],
      benefits: ["Softens frown and forehead lines", "Short appointment"],
      suitableFor: ["Forehead lines", "Frown lines", "Crow's feet"],
      duration: "15 – 20 minutes",
      faqs: [["When will I see the effect?", "It develops gradually over several days."]],
      related: ["dermal-fillers"],
    }),
  ],
};

const brand: BrandConfig = {
  id: ID,
  name: NAME,
  shortName: NAME,
  tagline: TAGLINE,
  intro: {
    eyebrow: "Welcome",
    heading: "A personalised approach to every treatment",
    text: [
      `${NAME} is a doctor-led aesthetic clinic in ${CITY}, bringing together medical expertise, personalised care and a natural approach.`, // PLACEHOLDER
      "Care begins with a consultation rather than a predetermined procedure. We explain the process, what to expect and the ongoing care involved.",
    ],
  },
  wordmark: WORDMARK,
  mark: EMBLEM,
  logo: LOGO,
  favicon: FAVICON,
  ogImage: OG_IMAGE,
  palette: COLORS,
  fonts: FONTS,
  siteUrl: SITE_URL,
  phone: CONTACT.phone,
  phoneTel: CONTACT.phoneTel,
  whatsapp: CONTACT.whatsapp,
  email: CONTACT.email,
  address: CONTACT.address,
  geo: CONTACT.geo,
  mapEmbedUrl: CONTACT.mapEmbedUrl,
  hours: CONTACT.hours,
  social: CONTACT.social,
  hero: {
    eyebrow: `${TAGLINE} · ${CITY}`,
    headline: "Skin and aesthetic care, led by a doctor", // PLACEHOLDER
    text: "A personalised plan for every patient, beginning with a consultation.",
    cta: "Book Consultation",
    image: HERO_IMAGE,
  },
  doctors: [
    {
      name: "Dr. Name Surname", // PLACEHOLDER
      title: "Founder & Lead Aesthetic Physician",
      credentials: "MBBS, MD", // PLACEHOLDER
      bio: ["[PLACEHOLDER] Training, qualifications, years of practice and registration details.", `Dr. Name leads ${NAME}.`],
      quote: "Treatment should begin with a consultation, not a predetermined procedure.",
      image: DOCTOR_IMAGE,
      specialties: ["Aesthetic medicine", "Injectables"],
    },
  ],
  team: [], // { name, role, image: img("alt", `${ASSETS}/team-1.jpg`) }; an empty list hides the section
  about: {
    heroHeading: "Medicine-led beauty, with a gentle touch",
    story: [`${NAME} was founded to bring careful, doctor-led aesthetic medicine to ${CITY}.`, "We keep appointments unhurried and explanations plain, so every decision is yours."], // PLACEHOLDER
    pullQuote: "Enhancement should feel natural, and the decision should always feel yours.",
    philosophy: [
      { title: "Natural balance", text: "Subtle, proportionate work that respects your features." },
      { title: "Medical standards", text: "Assessment, consent and aftercare at every step." },
      { title: "Honest guidance", text: "We say what a treatment can and cannot do." },
    ],
  },
  timeline: [
    { year: "20XX", title: `${NAME} opens`, text: "Placeholder milestone." }, // PLACEHOLDER
  ],
  categories: [skin, injectables],
  why: [
    { title: "Doctor-led", text: "Assessment and injectables performed by doctors." },
    { title: "Personalised plans", text: "Every plan follows a consultation, never a template." },
    { title: "Clear communication", text: "Steps, aftercare and expectations explained up front." },
    { title: "Calm, private setting", text: "Unhurried appointments in a discreet clinic." },
  ],
  testimonials: [
    { name: "Patient name", text: "PLACEHOLDER: replace with a real review you have written consent to publish.", rating: 5 },
  ],
  videoReviews: REELS,
  googleRating: GOOGLE_RATING,
  gallery: GALLERY,
  beforeAfter: [], // { id, title, categorySlug, treatment, before: img("Before", src), after: img("After", src), note: disclaimer }
  stats: [
    { value: "4", label: "Treatments offered" },
    { value: "2", label: "Treatment areas" },
    { value: "1:1", label: "Doctor consultation first" },
  ],
  homeFaqs: [
    faq("Do I need a consultation before treatment?", "Yes. A consultation lets our team understand your concerns, medical history and goals before recommending suitable options."),
    faq("Are results the same for everyone?", "No. Results vary from person to person."),
  ],
  seo: {
    title: `${NAME} | ${TAGLINE}, ${CITY}`,
    description: `Doctor-led aesthetic medicine in ${CITY}: skin health, injectables and personalised care.`, // PLACEHOLDER
    keywords: [`aesthetic clinic ${CITY}`],
  },
  redirects: {}, // old URL path -> new URL path (301), e.g. "/services": "/treatments"
  disclaimer,
};

export default brand;
